version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_CONNECTION: mysql
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234567890
      MYSQL_ROOT_PASSWORD: 1234567890

    networks:
      - app-network
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    container_name: pma
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge